version: '3.8'

services:
  db:
    image: postgres:14  # ou a versão que você deseja usar
    environment:
      POSTGRES_USER: postgres          # Nome do usuário
      POSTGRES_PASSWORD: Aran0805.     # Senha do usuário
      POSTGRES_DB: agendify            # Nome do banco de dados a ser criado
    ports:
      - "5432:5432"                     # Mapeia a porta do contêiner para a porta local
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistência dos dados

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:Aran0805.@db:5432/agendify"  # String de conexão ao banco de dados
    depends_on:
      - db                           # Garante que o serviço db esteja iniciado antes do app
    ports:
      - "3000:3000"                 # Mapeia a porta da aplicação

volumes:
  postgres_data:                   # Volume para persistir dados do PostgreSQL
